[project]
name = "uncertainty-aware-reasoning-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.7.2",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]
